### ISSUE TITLE
add balance to the transfer paper

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-pro#136]
Add a balance indicator so the user knows how much he can transfer (like deposit/withdraw paper)

![bildschirmfoto 2017-01-24 um 16 44 19](https://cloud.githubusercontent.com/assets/5337809/22254343/9ef25144-e254-11e6-82e2-1b4057a4486b.png)

**Comment by nanexcool** [comment]
@gbalabasquer pushed this to gonza/ui-new-design but Elio needs to look at the CSS. (Wallet balance is also clickable, and will fill the amount)

**Comment by elioosesconnaxis** [comment]
@nanexcool i fix this in gonza/ui-new-design:

![captura de pantalla 2017-01-24 a las 16 44 10](https://cloud.githubusercontent.com/assets/22946832/22263776/5d364aee-e254-11e6-8b24-3f9c0d1c876f.png)

**Comment by pimato** [comment]
could you make the wallet indicator exactly like this:

![bildschirmfoto 2017-01-24 um 21 35 45](https://cloud.githubusercontent.com/assets/5337809/22265642/306cffa2-e27d-11e6-9386-c54cdb6b2115.png)

**Comment by pimato** [comment]
still not looking like on the picture. There is still border on the bottom. 
(there is a reason why I am posting screenshots)

**Comment by gbalabasquer** [comment]
@pimato ok, I think we should fix it everywhere.
What I can understand is that the line means there is an input field. Is that correct?
Then we should check all the pop-ups as well because now every row has a line in the html. Which is not correct comparing to the design.
However if I check the design the owner row has also a line above and another below, that couldn't be confusing if the line means input field? even if this one is a bit darker than the other?

![image](https://cloud.githubusercontent.com/assets/12644398/22339940/789a1438-e3ca-11e6-8d94-88e7a89410da.png)

**Comment by pimato** [comment]
What I can understand is that the line means there is an input field. Is that correct?
**Right, the very close line below and the light grey color of the editable text are indicator for an Inputfield.**

Then we should check all the pop-ups as well because now every row has a line in the html. Which is not correct comparing to the design.
**You are right.**

However if I check the design the owner row has also a line above and another below, that couldn't be confusing if the line means input field? even if this one is a bit darker than the other?
**I don't think so. If we are going strict by the design, we shouldn't have a problem. Otherwise we are gonna change the owner row a little bit more so the user will not get confused.**

**Comment by gbalabasquer** [comment]
@pimato Ok great!
Can you confirm me the color code for the input bottom line? I noticed difference between the different blocks. I think the correct one is used in the sell and buy orders.

**Comment by pimato** [comment]
@gbalabasquer  yes : #F7F8F9 .

**Comment by gbalabasquer** [comment]
@pimato great, that was the one on the homepage. For the owner row, which would be the color? Sorry to ask but do not have access to the sketch easily now.

**Comment by pimato** [comment]
@gbalabasquer no problem at all :) . #E0E6E8

**Comment by gbalabasquer** [comment]
@pimato think is fine now but just fix the line thing. If there is something else, please let me know.

**Comment by pimato** [comment]
could you vertical align the three things, because the button got pushed down in this implementation. ( The Button should have the same margin-right,margin-bottom as like the deposit/withdraw button in the withdraw/deposit page.

![bildschirmfoto 2017-01-26 um 18 36 58](https://cloud.githubusercontent.com/assets/5337809/22343042/df1f2ce4-e3f6-11e6-830b-096857a64147.png)

![bildschirmfoto 2017-01-26 um 18 41 04](https://cloud.githubusercontent.com/assets/5337809/22343080/07f526aa-e3f7-11e6-957a-afa1c512f02d.png)

**Comment by gbalabasquer** [comment]
@pimato the button is not positioned respective the bottom, so had to do it manually. However I think looks the same.  As soon I upload this to surge you will be able to check it. On the right I see the same margin than the deposit one respecting the border of the paper.

**Comment by pimato** [comment]
<img width="466" alt="bildschirmfoto 2017-01-31 um 23 10 19" src="https://cloud.githubusercontent.com/assets/5337809/22486668/bc1d53a2-e80a-11e6-9367-27b8b7f8d5e8.png">

- the colors of both token indicators (wallet and amount) should have the same color.
- could you give the TextInputfield a hint text with "0x" so a user knows that he should put a address in it .

**Comment by pimato** [comment]
- The hint "0x" should have the same color as the amount "0"
