### ISSUE TITLE
unable to place buy order using metamask

### ISSUE THREAD

**Issue by ColinLeath** [OasisDEX/oasis-pro#164]
I'm unable to buy on mkr.market. The error is "Transaction nonce too low, try incrementing the nonce."

I'm not running my own node-- and I'm connected to the mainnet.

I also added this comment to the
Tx Transmission Failures - Widecast #839
issue at metamask
https://github.com/MetaMask/metamask-plugin/issues/839

https://github.com/MetaMask/metamask-plugin/issues/839#issuecomment-277062918

**Comment by kumavis** [comment]
sounds like you are using the same account in multiple clients - please (1) dont do that (2) refresh metamask
