### ISSUE TITLE
https://oasisdex.com SSL certificate is invalid.

### ISSUE THREAD

**Issue by MicahZoltu** [OasisDEX/oasis-pro#177]
I'm not sure what your mechanism is for getting SSL certificates, but the one currently being returned is for `*.github.com` and therefore not valid.

Personally, I have found that CloudFlare's free service is great for generally "solving" this whole class of problems (SSL, caching, CDN, etc.) with hardly any work.  You will have to use their name servers but it also makes it really easy to move your site (hosting) around transparently to end-users.

**Comment by reverendus** [comment]
Looks fine to me...
<img width="570" alt="screen shot 2017-02-24 at 12 49 05" src="https://cloud.githubusercontent.com/assets/10530476/23302613/a7898e14-fa8f-11e6-9fcb-b7295fa46b67.png">

Shall we close it..?

**Comment by MicahZoltu** [comment]
Looks fixed to me.
