### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by BasharAG** [OasisDEX/oasis-pro#199]
I followed all the steps and installed all the dependencies mentioned, but after running npm run build in the project's directory, I got this message:

root@www:~/oasis-pro# npm run build

```
> Maker-Market@ build /root/oasis-pro
> gulp build

[14:30:22] Using gulpfile ~/oasis-pro/gulpfile.js
[14:30:22] Starting 'build-dapple-maker-otc'...
[14:30:22] Starting 'build-dapple-token-wrapper'...
{ Error: Command failed: dapple build --template meteor --no-deploy-data
/bin/sh: 1: dapple: not found

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: 'dapple build --template meteor --no-deploy-data' }
[14:30:22] 'build-dapple-token-wrapper' errored after 4.98 ms
[14:30:22] Error: Command failed: dapple build --template meteor --no-deploy-data
/bin/sh: 1: dapple: not found

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
{ Error: Command failed: dapple build --template meteor --no-deploy-data
/bin/sh: 1: dapple: not found

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: 'dapple build --template meteor --no-deploy-data' }
[14:30:22] 'build-dapple-maker-otc' errored after 8.13 ms
[14:30:22] Error: Command failed: dapple build --template meteor --no-deploy-data
/bin/sh: 1: dapple: not found

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! Maker-Market@ build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Maker-Market@ build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Maker-Market package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Maker-Market
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Maker-Market
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/oasis-pro/npm-debug.log
```

**Comment by nanexcool** [comment]
Looks like you have not installed dapple. Run `npm install -g dapple` and try again!

**Comment by BasharAG** [comment]
Still didn't fix it :/

**Comment by nanexcool** [comment]
Can you show me the output of `dapple --version` and `solc --version` ?

Also did you install all of these?

* geth `brew install ethereum` (or [`apt-get` for ubuntu](https://github.com/ethereum/go-ethereum/wiki/Installation-Instructions-for-Ubuntu))
* solidity https://solidity.readthedocs.org/en/latest/installing-solidity.html
* meteor `curl https://install.meteor.com/ | sh`
* Global dapple, `npm install -g dapple meteor-build-client`

**Comment by BasharAG** [comment]
I installed all of these, still the same issue. The output for dapple --version is 0.8.47 and for solc --version is ```
solc the solidity compiler commandline interface
Version: 0.4.9+commit.364da425.Linux.g++
```

Below is the npm error log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@4.3.0
3 info using node@v7.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Maker-Market@~prebuild: Maker-Market@
6 silly lifecycle Maker-Market@~prebuild: no script for prebuild, continuing
7 info lifecycle Maker-Market@~build: Maker-Market@
8 verbose lifecycle Maker-Market@~build: unsafe-perm in lifecycle true
9 verbose lifecycle Maker-Market@~build: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/root/oasis-pro/node_modules/.bin:/usr/local/sb$
10 verbose lifecycle Maker-Market@~build: CWD: /root/oasis-pro
11 silly lifecycle Maker-Market@~build: Args: [ '-c', 'gulp build' ]
12 silly lifecycle Maker-Market@~build: Returned: code: 1  signal: null
13 info lifecycle Maker-Market@~build: Failed to exec build script
14 verbose stack Error: Maker-Market@ build: `gulp build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Maker-Market@
16 verbose cwd /root/oasis-pro
17 error Linux 4.4.0-64-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
19 error node v7.6.0
20 error npm  v4.3.0
21 error code ELIFECYCLE
22 error errno 1
23 error Maker-Market@ build: `gulp build`
23 error Exit status 1
24 error Failed at the Maker-Market@ build script 'gulp build'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the Maker-Market package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     gulp build
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs Maker-Market
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls Maker-Market
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by nanexcool** [comment]
I'm a bit stumped... Do you have `gulp` installed? Did you run `git submodule update --init --recursive` ?

**Comment by nanexcool** [comment]
Found the issue! There's a problem starting with solc 0.4.9 regarding calling internal constructors (I think).

The problem is with the Golem Token contract, used for our token wrapper.

Go to `dapple_packages/token-wrapper/src/golem_source.sol`

In line 235, remove the `internal` so it looks like this:

`function GNTAllocation(address _golemFactory) {`

And you can do `npm run build`.

**Comment by BasharAG** [comment]
That fixed it :) Thank you very much!

**Comment by pimato** [comment]
fixed and closed.
