### ISSUE TITLE
I would like to add my POWER4 token to your exchange

### ISSUE THREAD

**Issue by hamsterPWR4** [OasisDEX/oasis-pro#214]
I would like to add my POWER4 token to your exchange.
The token contract address is : 0x38124611aC29A3D54EeAaBb63742D5e62a5da0D4
The token owner address is : 0x0e1e7A8A20e79A87Ed69EA2d99c4663f72B018E2
I am almost done with my DAPP that will use this token.

Token will be used for lottery. 100 tokens = 1 ticket. 100 tokens will cost 0.001 Eth. That means that at current prices.. lets say $50 for one ether it will cost $0.05 cents per play. The lottery will pay out in the POWER4 token. There are some special features to it but essentially you can win as few as 4,300 POWER4 tokens that you can later sell for ether or keep to play more and I intend on buying them back for ether but also if you get all 4 lottery numbers 4 of 4 you will get 730,000 POWER4 tokens. Which again you can sell for 7,300 Ether or you can keep to play some more with them. I am considering using this token as a token for many other DAPPS, poker, lottery, and many other DAPPS in the work. I do not expect to mint any more I am a firm believer that as the creator I need to and will buy them back for ether. Thus creating a true supply and demand structure for my token. I plan on keeping the price fixed at 0.00001 per token although I have set some shares to 0.00002 on a different as well as 0.00001 for supply and demand issues. I do not plan on ever selling for more than 0.00002 and if I do it will be very rare. I plan to keep prices low. I like the idea of a lottery but $5 for a ticket or more at 0.1ether is too high. This is a supposed to be a fun thing that does not break banks. I will host two drawings per week. One on Wednesday and one on Saturday. 

Cheers laddies and gentleman! I you enjoy my DAPP and accompanying Token

**Comment by Rune23** [comment]
Sorry but as there is no way to determine if this is a scam it can't be added for now. What you should do is fork our code and deploy your own oasis contract and frontend, and then market it independently. If you manage to attract an organic community around your project then it will be possible for us to add it to the main OasisDEX frontend.

**Comment by ryepdx** [comment]
You should probably verify your contract's code on Etherscan.
