### ISSUE TITLE
MKR Withdrawal

### ISSUE THREAD

**Issue by tlogs5344** [OasisDEX/oasis-pro#217]
I may be mistaken, but it doesn't seem like Oasis Pro enables users to withdraw MKR tokens purchased within. Is this correct? If so, will the ability to withdraw MKR tokens be enabled in the future?

Thank you.

**Comment by nanexcool** [comment]
If you bought MKR, you should have them in the address you used to buy an offer. You can go to the Transfer tab to send them to a different account.

There's no concept of "withdrawing" MKR. If you create a MKR sell order, you send MKR to the market to hold in escrow. If you cancel the order, you get the MKR back. If you create a buy order, you send WETH to the market. Hope I made myself clear.

**Comment by tlogs5344** [comment]
Thank you very much nanexcool! That makes great sense. Loving these decentralized exchanges
